# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1397, 917)
        self.container = QtWidgets.QWidget(MainWindow)
        self.container.setObjectName("container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainBox = QtWidgets.QVBoxLayout()
        self.mainBox.setObjectName("mainBox")
        self.topBox = QtWidgets.QHBoxLayout()
        self.topBox.setContentsMargins(-1, 0, 0, -1)
        self.topBox.setObjectName("topBox")
        self.camBtn_open = QtWidgets.QPushButton(self.container)
        self.camBtn_open.setEnabled(True)
        self.camBtn_open.setMinimumSize(QtCore.QSize(100, 40))
        self.camBtn_open.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.camBtn_open.setFont(font)
        self.camBtn_open.setIconSize(QtCore.QSize(20, 20))
        self.camBtn_open.setCheckable(False)
        self.camBtn_open.setObjectName("camBtn_open")
        self.topBox.addWidget(self.camBtn_open)
        self.camBtn_stop = QtWidgets.QPushButton(self.container)
        self.camBtn_stop.setEnabled(True)
        self.camBtn_stop.setMinimumSize(QtCore.QSize(100, 40))
        self.camBtn_stop.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.camBtn_stop.setFont(font)
        self.camBtn_stop.setObjectName("camBtn_stop")
        self.topBox.addWidget(self.camBtn_stop)
        self.Picture_edit = QtWidgets.QPushButton(self.container)
        self.Picture_edit.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Picture_edit.setFont(font)
        self.Picture_edit.setObjectName("Picture_edit")
        self.topBox.addWidget(self.Picture_edit)
        self.Page_Label = QtWidgets.QLabel(self.container)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Page_Label.setFont(font)
        self.Page_Label.setText("")
        self.Page_Label.setObjectName("Page_Label")
        self.topBox.addWidget(self.Page_Label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topBox.addItem(spacerItem)
        self.mainBox.addLayout(self.topBox)
        self.midBox = QtWidgets.QHBoxLayout()
        self.midBox.setObjectName("midBox")
        self.Previous_btn = QtWidgets.QPushButton(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Previous_btn.sizePolicy().hasHeightForWidth())
        self.Previous_btn.setSizePolicy(sizePolicy)
        self.Previous_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Previous_btn.setFont(font)
        self.Previous_btn.setObjectName("Previous_btn")
        self.midBox.addWidget(self.Previous_btn)
        self.view = QtWidgets.QScrollArea(self.container)
        self.view.setMinimumSize(QtCore.QSize(670, 670))
        self.view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.view.setWidgetResizable(True)
        self.view.setObjectName("view")
        self.viewForm = QtWidgets.QWidget()
        self.viewForm.setGeometry(QtCore.QRect(0, 0, 1147, 761))
        self.viewForm.setObjectName("viewForm")
        self.viewData = QtWidgets.QLabel(self.viewForm)
        self.viewData.setGeometry(QtCore.QRect(0, 0, 650, 650))
        self.viewData.setMinimumSize(QtCore.QSize(650, 650))
        self.viewData.setMaximumSize(QtCore.QSize(650, 650))
        self.viewData.setText("")
        self.viewData.setObjectName("viewData")
        self.view.setWidget(self.viewForm)
        self.midBox.addWidget(self.view)
        self.Next_btn = QtWidgets.QPushButton(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Next_btn.sizePolicy().hasHeightForWidth())
        self.Next_btn.setSizePolicy(sizePolicy)
        self.Next_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Next_btn.setFont(font)
        self.Next_btn.setObjectName("Next_btn")
        self.midBox.addWidget(self.Next_btn)
        self.mainBox.addLayout(self.midBox)
        self.bottomBox = QtWidgets.QHBoxLayout()
        self.bottomBox.setObjectName("bottomBox")
        self.viewCbo_roi = QtWidgets.QComboBox(self.container)
        self.viewCbo_roi.setMinimumSize(QtCore.QSize(100, 26))
        self.viewCbo_roi.setMaximumSize(QtCore.QSize(80, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.viewCbo_roi.setFont(font)
        self.viewCbo_roi.setMaxVisibleItems(10)
        self.viewCbo_roi.setObjectName("viewCbo_roi")
        self.viewCbo_roi.addItem("")
        self.viewCbo_roi.addItem("")
        self.viewCbo_roi.addItem("")
        self.viewCbo_roi.addItem("")
        self.viewCbo_roi.addItem("")
        self.viewCbo_roi.addItem("")
        self.bottomBox.addWidget(self.viewCbo_roi)
        self.radio_Normal = QtWidgets.QRadioButton(self.container)
        self.radio_Normal.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radio_Normal.setFont(font)
        self.radio_Normal.setChecked(True)
        self.radio_Normal.setObjectName("radio_Normal")
        self.bottomBox.addWidget(self.radio_Normal)
        self.radio_SmallTubid = QtWidgets.QRadioButton(self.container)
        self.radio_SmallTubid.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radio_SmallTubid.setFont(font)
        self.radio_SmallTubid.setObjectName("radio_SmallTubid")
        self.bottomBox.addWidget(self.radio_SmallTubid)
        self.radio_Turbid = QtWidgets.QRadioButton(self.container)
        self.radio_Turbid.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radio_Turbid.setFont(font)
        self.radio_Turbid.setObjectName("radio_Turbid")
        self.bottomBox.addWidget(self.radio_Turbid)
        self.save_btn = QtWidgets.QPushButton(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_btn.sizePolicy().hasHeightForWidth())
        self.save_btn.setSizePolicy(sizePolicy)
        self.save_btn.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_btn.setFont(font)
        self.save_btn.setObjectName("save_btn")
        self.bottomBox.addWidget(self.save_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomBox.addItem(spacerItem1)
        self.mainBox.addLayout(self.bottomBox)
        self.horizontalLayout_2.addLayout(self.mainBox)
        MainWindow.setCentralWidget(self.container)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")

        self.retranslateUi(MainWindow)
        self.viewCbo_roi.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Doctor Label"))
        self.camBtn_open.setText(_translate("MainWindow", "Open"))
        self.camBtn_stop.setText(_translate("MainWindow", "Stop"))
        self.Picture_edit.setText(_translate("MainWindow", "Edit"))
        self.Previous_btn.setText(_translate("MainWindow", "Previous"))
        self.Next_btn.setText(_translate("MainWindow", "Next"))
        self.viewCbo_roi.setItemText(0, _translate("MainWindow", "0.50"))
        self.viewCbo_roi.setItemText(1, _translate("MainWindow", "0.75"))
        self.viewCbo_roi.setItemText(2, _translate("MainWindow", "1.00"))
        self.viewCbo_roi.setItemText(3, _translate("MainWindow", "1.25"))
        self.viewCbo_roi.setItemText(4, _translate("MainWindow", "1.50"))
        self.viewCbo_roi.setItemText(5, _translate("MainWindow", "0.25"))
        self.radio_Normal.setText(_translate("MainWindow", "Normal"))
        self.radio_SmallTubid.setText(_translate("MainWindow", "SmallTurbid"))
        self.radio_Turbid.setText(_translate("MainWindow", "Turbid"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))

